// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAssistant.Api.Data;

#nullable disable

namespace SmartAssistant.Core.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302103928_AddAutomationLastRunFields")]
    partial class AddAutomationLastRunFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartAssistant.Core.Entities.EmailOAuthAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailOAuthAccounts");
                });

            modelBuilder.Entity("SmartAssistant.Core.Entities.EmailProcessed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "MessageId")
                        .IsUnique();

                    b.ToTable("EmailProcessed");
                });

            modelBuilder.Entity("SmartAssistant.Core.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReminderTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type", "SourceProvider", "SourceId")
                        .IsUnique()
                        .HasFilter("[SourceProvider] IS NOT NULL AND [SourceId] IS NOT NULL");

                    b.ToTable("Reminder");
                });

            modelBuilder.Entity("SmartAssistant.Core.Entities.ReminderAutomationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultReminderAfterMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("GmailQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeywordsCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastRunCreatedCount")
                        .HasColumnType("int");

                    b.Property<string>("LastRunError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastRunOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScanIntervalMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReminderAutomationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultReminderAfterMinutes = 60,
                            Enabled = true,
                            GmailQuery = "in:inbox newer_than:7d -category:promotions -category:social",
                            KeywordsCsv = "action required,urgent,asap,deadline,meeting,invoice,follow up",
                            LastRunCreatedCount = 0,
                            ScanIntervalMinutes = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
